version: '3'

services:
  nginx:
    build:
      context: .
      args:
        - SPIN_UID=503
        - SPIN_GID=20
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/conf.d
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - NGINX_SERVICE_ROOT_URL=service-root:80
      - NGINX_SERVICE_1_URL=service-1:80
      - NGINX_SERVICE_2_URL=service-2:80
      - NGINX_SERVICE_ROOT_LOCATION=/
      - NGINX_SERVICE_1_LOCATION=/service_1
      - NGINX_SERVICE_2_LOCATION=/service_2
      - NGINX_SERVER_NAME=localhost
      - NGINX_CERT_EMAIL=gprodrigoalvarez@lbl.gov
    depends_on:
      - service-root
      - service-1
      - service-2
  service-root:
    image: httpd:2.4
    volumes:
      - ./htdocs_service_root:/usr/local/apache2/htdocs/
  service-1:
    image: httpd:2.4
    volumes:
      - ./htdocs_service_1:/usr/local/apache2/htdocs/
  service-2:
    image: httpd:2.4
    volumes:
      - ./htdocs_service_2:/usr/local/apache2/htdocs/
  